services:
- type: web
  name: pdf-tools
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
  port: 10000
  envVars:
  - key: PYTHON_VERSION
    value: 3.9.5
